create table User (id integer generated by default as identity, adress varchar(255), email varchar(255), name varchar(255), password varchar(255), phone_number varchar(255), surname varchar(255), primary key (id));

INSERT INTO User VALUES(1, 'adresas1', 'Tomas@gmail.com','Tomas', 'pass', '+37060111111', 'surname1');
INSERT INTO User VALUES(2, 'adresas2', 'Jonas@gmail.com','Jonas', 'pass', '+37060222222', 'surname2');
INSERT INTO User VALUES(3, 'adresas3', 'Petras@gmail.com','Petras', 'pass', '+37060333333', 'surname3');





